spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rentcars240423
    username: postgres
    password: 123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: alkam2022820@gmail.com
    password: ezmmvparnglwyrft
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  mvc:
    path match:
      matching-strategy: ant_path_matcher